services:

  ratelimiter:
    build: .
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"