// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v6.31.1
// source: api/proto/ratelimit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShouldAllowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Limit int64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ShouldAllowRequest) Reset() {
	*x = ShouldAllowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_ratelimit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldAllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldAllowRequest) ProtoMessage() {}

func (x *ShouldAllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldAllowRequest.ProtoReflect.Descriptor instead.
func (*ShouldAllowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *ShouldAllowRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ShouldAllowRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ShouldAllowRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ShouldAllowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
}

func (x *ShouldAllowResponse) Reset() {
	*x = ShouldAllowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_ratelimit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldAllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldAllowResponse) ProtoMessage() {}

func (x *ShouldAllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldAllowResponse.ProtoReflect.Descriptor instead.
func (*ShouldAllowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *ShouldAllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_api_proto_ratelimit_proto protoreflect.FileDescriptor

var file_api_proto_ratelimit_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x65,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x50, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x32, 0x64, 0x0a, 0x12, 0x52, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x1d,
	0x2e, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c,
	0x64, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x62,
	0x68, 0x69, 0x73, 0x68, 0x65, 0x6b, 0x64, 0x78, 0x33, 0x30, 0x30, 0x2f, 0x72, 0x61, 0x74, 0x65,
	0x2d, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_ratelimit_proto_rawDescOnce sync.Once
	file_api_proto_ratelimit_proto_rawDescData = file_api_proto_ratelimit_proto_rawDesc
)

func file_api_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_api_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_api_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_ratelimit_proto_rawDescData)
	})
	return file_api_proto_ratelimit_proto_rawDescData
}

var file_api_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ratelimit_proto_goTypes = []interface{}{
	(*ShouldAllowRequest)(nil),  // 0: ratelimit.ShouldAllowRequest
	(*ShouldAllowResponse)(nil), // 1: ratelimit.ShouldAllowResponse
}
var file_api_proto_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.RateLimiterService.ShouldAllow:input_type -> ratelimit.ShouldAllowRequest
	1, // 1: ratelimit.RateLimiterService.ShouldAllow:output_type -> ratelimit.ShouldAllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ratelimit_proto_init() }
func file_api_proto_ratelimit_proto_init() {
	if File_api_proto_ratelimit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_ratelimit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldAllowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_ratelimit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldAllowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_ratelimit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_api_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_api_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_api_proto_ratelimit_proto = out.File
	file_api_proto_ratelimit_proto_rawDesc = nil
	file_api_proto_ratelimit_proto_goTypes = nil
	file_api_proto_ratelimit_proto_depIdxs = nil
}
